// The interop harness gRPC surface: exactly one protected operation, as the
// harness contract requires (../../CONTRACT.md). Every entry declaring a gRPC
// role implements this service; the go-0.12 reference entry defines it.
//
// In signed mode the request payload is empty and the credential rides in
// metadata (valiss-account-token, valiss-user-token, valiss-timestamp,
// valiss-signature, valiss-nonce). In message mode the payload carries the
// message bytes the token's checksum is bound to, and the token rides in
// valiss-message-token metadata.
//
// Accept: OK, with the response json field carrying the contract's accept
// shape. Reject: UNAUTHENTICATED, with the status message carrying the
// contract's reject JSON.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v7.35.1
// source: interop.proto

package interoppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// payload is the message-mode body; empty in signed mode.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_interop_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// json is the contract accept shape:
	// {"ok": true, "tenant": ..., "user": ...|null}.
	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_interop_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_interop_proto protoreflect.FileDescriptor

var file_interop_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x76, 0x61, 0x6c, 0x69, 0x73, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x2e,
	0x76, 0x31, 0x22, 0x29, 0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x24, 0x0a,
	0x0e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a,
	0x73, 0x6f, 0x6e, 0x32, 0x58, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x12, 0x4d,
	0x0a, 0x06, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x20, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x73,
	0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x76, 0x61, 0x6c,
	0x69, 0x73, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3c, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x73, 0x73, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x2f, 0x68,
	0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x30, 0x2e, 0x31, 0x33, 0x72, 0x63,
	0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_interop_proto_rawDescOnce sync.Once
	file_interop_proto_rawDescData = file_interop_proto_rawDesc
)

func file_interop_proto_rawDescGZIP() []byte {
	file_interop_proto_rawDescOnce.Do(func() {
		file_interop_proto_rawDescData = protoimpl.X.CompressGZIP(file_interop_proto_rawDescData)
	})
	return file_interop_proto_rawDescData
}

var file_interop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interop_proto_goTypes = []interface{}{
	(*InvokeRequest)(nil),  // 0: valiss.interop.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: valiss.interop.v1.InvokeResponse
}
var file_interop_proto_depIdxs = []int32{
	0, // 0: valiss.interop.v1.Interop.Invoke:input_type -> valiss.interop.v1.InvokeRequest
	1, // 1: valiss.interop.v1.Interop.Invoke:output_type -> valiss.interop.v1.InvokeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interop_proto_init() }
func file_interop_proto_init() {
	if File_interop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interop_proto_goTypes,
		DependencyIndexes: file_interop_proto_depIdxs,
		MessageInfos:      file_interop_proto_msgTypes,
	}.Build()
	File_interop_proto = out.File
	file_interop_proto_rawDesc = nil
	file_interop_proto_goTypes = nil
	file_interop_proto_depIdxs = nil
}
