// The interop harness gRPC surface: exactly one protected operation, as the
// harness contract requires (../../CONTRACT.md). Every entry declaring a gRPC
// role implements this service; the go-0.12 reference entry defines it.
//
// In signed mode the request payload is empty and the credential rides in
// metadata (valiss-account-token, valiss-user-token, valiss-timestamp,
// valiss-signature, valiss-nonce). In message mode the payload carries the
// message bytes the token's checksum is bound to, and the token rides in
// valiss-message-token metadata.
//
// Accept: OK, with the response json field carrying the contract's accept
// shape. Reject: UNAUTHENTICATED, with the status message carrying the
// contract's reject JSON.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: interop.proto

package interoppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the message-mode body; empty in signed mode.
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_interop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_interop_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// json is the contract accept shape:
	// {"ok": true, "tenant": ..., "user": ...|null}.
	Json          string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_interop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_interop_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_interop_proto protoreflect.FileDescriptor

const file_interop_proto_rawDesc = "" +
	"\n" +
	"\rinterop.proto\x12\x11valiss.interop.v1\")\n" +
	"\rInvokeRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"$\n" +
	"\x0eInvokeResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json2X\n" +
	"\aInterop\x12M\n" +
	"\x06Invoke\x12 .valiss.interop.v1.InvokeRequest\x1a!.valiss.interop.v1.InvokeResponseB9Z7github.com/valiss-dev/interop/harness/go-0.12/interoppbb\x06proto3"

var (
	file_interop_proto_rawDescOnce sync.Once
	file_interop_proto_rawDescData []byte
)

func file_interop_proto_rawDescGZIP() []byte {
	file_interop_proto_rawDescOnce.Do(func() {
		file_interop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interop_proto_rawDesc), len(file_interop_proto_rawDesc)))
	})
	return file_interop_proto_rawDescData
}

var file_interop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interop_proto_goTypes = []any{
	(*InvokeRequest)(nil),  // 0: valiss.interop.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: valiss.interop.v1.InvokeResponse
}
var file_interop_proto_depIdxs = []int32{
	0, // 0: valiss.interop.v1.Interop.Invoke:input_type -> valiss.interop.v1.InvokeRequest
	1, // 1: valiss.interop.v1.Interop.Invoke:output_type -> valiss.interop.v1.InvokeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interop_proto_init() }
func file_interop_proto_init() {
	if File_interop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interop_proto_rawDesc), len(file_interop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interop_proto_goTypes,
		DependencyIndexes: file_interop_proto_depIdxs,
		MessageInfos:      file_interop_proto_msgTypes,
	}.Build()
	File_interop_proto = out.File
	file_interop_proto_goTypes = nil
	file_interop_proto_depIdxs = nil
}
