// The interop harness gRPC surface: exactly one protected operation, as the
// harness contract requires (../../CONTRACT.md). Every entry declaring a gRPC
// role implements this service; the go-0.12 reference entry defines it.
//
// In signed mode the request payload is empty and the credential rides in
// metadata (valiss-account-token, valiss-user-token, valiss-timestamp,
// valiss-signature, valiss-nonce). In message mode the payload carries the
// message bytes the token's checksum is bound to, and the token rides in
// valiss-message-token metadata.
//
// Accept: OK, with the response json field carrying the contract's accept
// shape. Reject: UNAUTHENTICATED, with the status message carrying the
// contract's reject JSON.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: interop.proto

package interoppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Interop_Invoke_FullMethodName = "/valiss.interop.v1.Interop/Invoke"
)

// InteropClient is the client API for Interop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteropClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type interopClient struct {
	cc grpc.ClientConnInterface
}

func NewInteropClient(cc grpc.ClientConnInterface) InteropClient {
	return &interopClient{cc}
}

func (c *interopClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, Interop_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteropServer is the server API for Interop service.
// All implementations must embed UnimplementedInteropServer
// for forward compatibility.
type InteropServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	mustEmbedUnimplementedInteropServer()
}

// UnimplementedInteropServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteropServer struct{}

func (UnimplementedInteropServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInteropServer) mustEmbedUnimplementedInteropServer() {}
func (UnimplementedInteropServer) testEmbeddedByValue()                 {}

// UnsafeInteropServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteropServer will
// result in compilation errors.
type UnsafeInteropServer interface {
	mustEmbedUnimplementedInteropServer()
}

func RegisterInteropServer(s grpc.ServiceRegistrar, srv InteropServer) {
	// If the following call panics, it indicates UnimplementedInteropServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Interop_ServiceDesc, srv)
}

func _Interop_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteropServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interop_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteropServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Interop_ServiceDesc is the grpc.ServiceDesc for Interop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "valiss.interop.v1.Interop",
	HandlerType: (*InteropServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Interop_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interop.proto",
}
